### ISSUE TITLE
launching QT Designer

### ISSUE THREAD

**Issue by swharden** [altendky/pyqt5-tools#2]
It was a little less than trivial for me to figure out how to launch the QT designer (the official distribution puts shortcuts everywhere).

FYI it's `Lib\site-packages\pyqt5-tools\designer\designer.exe` and it might be worth noting this on the [long_description](https://github.com/altendky/pyqt5-tools/blob/master/setup.py#L9)

**Comment by altendky** [comment]
I agree.  Python packages are generally not intended to provide 'outside of Python environment' installation features such as shortcuts etc, but it would probably be reasonable to install a script with it that could be run to create such links if desired.

If I overcome the PyPi issues mentioned in #1 then I'll try go address this as well.

**Comment by akej74** [comment]
Just a side-note, you can install QT Designer "stand-alone" as follows:

1. Install latest QT (I'm using 5.8) from [QT main site](https://www.qt.io/)
2. Make sure you include "Qt 5.8 MinGW" component
3. QT Designer will be installed in` C:\Qt\5.8\mingw53_32\bin\designer.exe`
4. Note that the executable is named "designer.exe"

**Comment by altendky** [comment]
@akej74 what that is missing is the PyQt5 designer plugin.  But, FYI:

1) There are now builds on PyPi for 5.8.2 and 5.7.1 for Python 3.6 and 3.5 for both 32 and 64 bit.  Note that they are marked RC but since I have no full releases yet they should still install without using `--pre`.
2) They are missing the web engine EXEs and libs since that dropped the size from 130MB to 30MB.

And no, this hasn't addressed this issue yet...

**Comment by akej74** [comment]
Hi @altendky , I just reinstalled my machine and installed the latest version of pyqt5-tools (**5.11.2.1.3rc6**), it's so nice to be able to get QT Designer without having to download GB's of stuff from QT. Thank you for providing this tool!

Side note: I'm using Python 3.6 while waiting for PyInstaller to support 3.7.

**Comment by altendky** [comment]
v1.3 released: https://www.riverbankcomputing.com/pipermail/pyqt/2018-September/040940.html
