### ISSUE TITLE
Version for PyQt5.12.x

### ISSUE THREAD

**Issue by zdenop** [altendky/pyqt5-tools#26]
Can you please create new version for recent version (5.12.1) PyQt5?
Your package requires PyQt5==5.11.3

**Comment by altendky** [comment]
@zdenop, my apologies for the delay on that.  To maintain coverage I really need to change some stuff around including archiving everything I use (SIP downloads etc) and getting a setup where I can have arbitrary Qt versions installed...  but I'll try to get something out in the mean time as well.  Thanks for the reminder.

**Comment by altendky** [comment]
@zdenop, not that the task is complete but if you want to grab some wheels manually, the 5.12 builds succeeded.

https://ci.appveyor.com/project/KyleAltendorf/pyqt5-tools/builds/23543830

**Comment by zdenop** [comment]
Thanks!

**Comment by sha-fuq** [comment]
Hi there, i too am in need of the 5.12.1 version. Would really appreciate the release. I looked at the link you provided but didn't really understand what to do there. Do you have an ETA for pyqt5-tools 5.12.1?

**Comment by altendky** [comment]
@sha-fuq finally got the build going again and it's pushing out v1.5rc4 with PyQt5.12.1.  You may need to pass `--pre` (pre-release) to `pip` to get it depending exactly how you install.

build progress: https://ci.appveyor.com/project/KyleAltendorf/pyqt5-tools/builds/24052250
PyPI downloads: https://pypi.org/project/pyqt5-tools/5.12.1.1.5rc4/#files

FYI, each job/row in the build is a different combination of PyQt and Python versions (and 32/64 bit).  If you click one of them you can then click 'artifacts' and download the wheel for that job.  This lets you get and use wheels that haven't made it to PyPI yet.  But, for now just wait for the build to get the 'version' you need uploaded to PyPI.

**Comment by sha-fuq** [comment]
@altendky Thank you so much! I might wait a bit for the stable release. If it doesn't come out soon enough I'll go ahead with your RC. Also I appreciate the explanation towards the non pypi wheels. Just to clarify, once a wheel is downloaded, how does one implement it? copy paste the file to a certain location or is there some kind of pip installation required?

**Comment by altendky** [comment]
@sha-fuq `yourenv/Scripts/pip install path/to/the.whl` or even `yourenv/scripts/pip install https://blah/blue/red.whl`.  As to a 'stable' release...  not much point in waiting.  It won't be 'more stable' than what's there unless someone finds a bug and I find time to fix it.  I use RC for 'testing' or in this case because I hadn't taken the time to think through what the next release should be.  The big issue right now is not having the versions of Qt I want available on AppVeyor so PyQt5.11 isn't building right now.  I need to explore installing Qt on Azure and see if that'll be a workable build platform where I can get whatever Qt version I feel like.

**Comment by sha-fuq** [comment]
Hi again, I installed the latest RC. I have 2 questions.

I made a new venv named designer and installed the package there. Does it make a difference whether I just double click the "designer.exe" from Windows Explorer? Or is it better to activate my venv and launch it from there? Also I see a pyqt5designer.exe which the program also launches with a cmd prompt on the background when I use that. But at the end of the prompt there is a line saying "QT_DEBUG_PLUGINS is not set". The program seems to work but just wanted to let you know.

Also I can't launch the help files within designer. When I click on Qt Designer Help it says: "The binary ..../Qt/bin/bin\assistant.exe does not exist".

Maybe this was how it was with previous editions. But since it's my first time using this module I wanted to let you know. Thanks for all your help!

**Comment by altendky** [comment]
No need to activate a venv, I rarely do.  Mostly that just adjusts your `$PATH` variable so that the executables in the env will be found first.  Even for Python in the shell I mostly just `venv/scripts/python`.

The `designer.exe` should be 'just Qt Designer'.  `pyqt5designer.exe` is a wrapper I wrote which provides cli access to a few things that normally aren't and also loads the PyQt5 Designer plugin.  The plugin is needed if you use custom widgets in designer which are written using PyQt5.  The wrapper is described in the readme.

https://github.com/altendky/pyqt5-tools#designer

The last point seems to be https://github.com/altendky/pyqt5-tools/issues/5.

**Comment by sha-fuq** [comment]
@altendky I'll follow your lead and just use designer.exe as a stand alone program to make my gui and convert it using the pyuic tool like I always do. Tested it with my program and everything seems to be working fine. Thank you for all your help and support!

**Comment by altendky** [comment]
Release packages should be up.  Please let me know if they work for you.

**Comment by altendky** [comment]
No complaints and old so closing.  Probably open a new issue if you are still having problems.
