### ISSUE TITLE
Merge PyQt5 with pyqt5-tools?

### ISSUE THREAD

**Issue by hiccup7** [altendky/pyqt5-tools#3]
Presently, pyqt5-tools has redundant files with https://pypi.python.org/pypi/PyQt5/ making the download much larger.  Do I understand correctly that pyqt5-tools is specific to a particular version of PyQt5?  If so, how about creating a variation of pyqt5-tools that is a merge of the two?  This would eliminate redundant files.  I am hoping the merged version would reduce the probability of bugs too.  If the download size is small enough, I am also hoping it will be included with the WinPython distribution, which used to include Qt Designer with PyQt4.

**Comment by altendky** [comment]
The `pyqt5` package is intended to provide the necessary support files for a PyQt5 application so it should not contain all the Qt development tools.  On the other hand, perhaps you are suggesting a package such as `pyqt5-with-tools` which a developer would install instead of `pyqt5`?  Maybe.

I don't expect to get to it soon but if I were to refine this package I would likely try to break it up and possibly add a dependency on the `pyqt5` package then somehow get the Qt applications to use the `pyqt5`-provided DLLs.

If I remember correctly the only PyQt5 related stuff in this package is the Designer plugin that allows Qt Designer to show PyQt5 widgets in its widget list.

**Comment by hiccup7** [comment]
>  On the other hand, perhaps you are suggesting a package such as pyqt5-with-tools which a developer would install instead of pyqt5?

Yes.  I realize that other packages, such as Spyder and matplotlib, will look for `pyqt5` as a dependency.  They will break if `pyqt5-with-tools` cannot be imported exactly as `pyqt5`.

What is the file size of the Designer plugin?

**Comment by altendky** [comment]
The designer .DLL (`pyqt5.dll`) is 29 KB.

Are you saying that yes, you would prefer a `pyqt5-with-tools` package?  As mentioned before this wouldn't be my preferred solution but I want to make sure I understand your desires.

**Comment by hiccup7** [comment]
Now that I understand the redundancy between `pyqt5` and `pyqt5-tools` is only 29KB, I think the development and maintenance is not worth while to create a `pyqt5-with-tools` package to reduce the download size.  Thank you for the explanation.  And thanks again for creating and maintaining `pyqt5-tools` for the Python community.

**Comment by altendky** [comment]
The Designer .DLL isn't in `pyqt5`...  :]  I think the redundancy would be the Qt .DLLs which could be more megabytes.

**Comment by hiccup7** [comment]
You can add the sizes of the Qt .DLLs and decide if `pyqt5-with-tools` is worth the effort.

**Comment by pe224** [comment]
From a quick check in the root directory of `pyqt5-tools` and the `Qt/bin` directory of `pyqt5` the redundancy seems more like 700MB.
If `pyqt5-tools` could depend on the `pyqt5`-provided DLLs that would probably the best solution.

**Comment by altendky** [comment]
@pe224 Where do you get 700MB of redundancy?  My entire `venv\Lib\site-packages\PyQt5` directory is only 155MB.  In this particular case it is PyQt5 5.8.2

**Comment by altendky** [comment]
1) There are now builds on PyPi for 5.8.2 and 5.7.1 for Python 3.6 and 3.5 for both 32 and 64 bit.  Note that they are marked RC but since I have no full releases yet they should still install without using `--pre`.
2) They are missing the web engine EXEs and libs since that dropped the size from 130MB to 30MB.

For now I think that 30MB is sufficiently small to not care about sharing files with PyQt5.  If there are significant concerns about size then perhaps it can be addressed later but for now I need to get back to other tasks.
