### ISSUE TITLE
Where's the main code

### ISSUE THREAD

**Issue by sc-1123** [altendky/pyqt5-tools#33]
Where's the main code?

**Comment by altendky** [comment]
`pyqt5-tools` just packages up existing Qt tools binaries and builds a couple PyQt5 plugins that aren't otherwise available as binaries with a little bit of cli wrapping.  So in some sense, there simply isn't any 'main code'.  If there's something particular you wanted to look at I might be able to point you in a useful direction though.

**Comment by altendky** [comment]
Let me know if you have any follow up questions.
