### ISSUE TITLE
Is there any plan to upgrade to pyqt 5.7.1 with the support for python3.6?

### ISSUE THREAD

**Issue by xin053** [altendky/pyqt5-tools#4]
If there is, thanks a lot.

**Comment by altendky** [comment]
I do apologize for not responding, though that's probably a sufficient answer.  :[  There is presently no 'plan' to do so.  That said, I'm not exactly sure what the difference would be.  This package is entirely Qt programs except for the Designer plugin and I don't recall off-hand how it ends up connecting to python.

All this said, I would 'like' to actually maintain and tidy this package.  But, I've got a lot of cleanup work to do in my own code...

**Comment by xin053** [comment]
OK, I understand. When I search for questions about how to get `qtdesigner.exe` after installing pyqt5 through `pip install pyqt5`, Many answers are `pyqt5-tools`. And it works well.

I am sorry for what you said. But I understand that. I appreciate for what you have done.

Finally, I install `qt creator` to solve this problem.

**Comment by altendky** [comment]
Out of curiosity, did you get an error message using `pyqt5-tools`?

**Comment by xin053** [comment]
`pyqt5-tools v5.7.dev10` works very well. Actually I just need `designer.exe` to design the GUI of my software.

**Comment by Jendarran** [comment]
I got said error message when attempting to install pyqt5-tools on Python 3.6.0. Like this:

Could not find a version that satisfies the requirement pyqt5-tools (from versions: )
No matching distribution found for pyqt5-tools

**Comment by altendky** [comment]
Yep, no 3.6.0 release presently, only 3.5.2 I think.  But do note that the file on PyPi (such as would be downloaded by `pip install pyqt5-tools`) is out of date and you want the one from GitHub (`pip install <url for .whl>` with the appropriate wheel from https://github.com/altendky/pyqt5-tools/releases/tag/v5.7.dev10).  There's some inkling that I might have a little time to work on this in the next month, but I'm still not betting on it.

**Comment by pe224** [comment]
I downloaded the most recent wheel from Github and renamed `cp35` to `cp36` to force pip to ignore the platform mismatch (my Python is 3.6.0).
It installs fine and the designer works. As mentioned in a different issue there seems not much python-specific content in pyqt5-tools. Do you think it is reasonable to upload the renamed wheel to PyPi so that `pip install pqyt5-tools` does not fail for the most recent Python version?
Also, the redundancy in PyQt5 DLLs both present in pyqt5 and pyqt5-tools is (quickly estimated) more like 700 MB.
Thanks.

**Comment by altendky** [comment]
The latest isn't on PyPi because it was too big. I hear they may make exceptions though. More importantly last week I was working on setting up builds on AppVeyor. Perhaps I will continue that effort and get some real builds to share. If I do then making it more space efficient will be considered.

**Comment by altendky** [comment]
1) There are now builds on PyPi for 5.8.2 and 5.7.1 for Python 3.6 and 3.5 for both 32 and 64 bit.  Note that they are marked RC but since I have no full releases yet they should still install without using `--pre`.
2) They are missing the web engine EXEs and libs since that dropped the size from 130MB to 30MB.

I'm going to go ahead and close this since the original question has been answer (first 'no', and now 'yes').  If there are issues, please open a new ticket and let me know.
